# Generated by Django 2.2.5 on 2019-10-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacurso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='categoriacurso',
            name='desripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cursocontenido',
            name='recursos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roles',
            name='desripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='escala',
            field=models.IntegerField(),
        ),
    ]
