# Generated by Django 2.2.5 on 2019-10-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20191010_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'ordering': ['nombre'], 'verbose_name': 'CategoriaCurso', 'verbose_name_plural': 'CategoriaCursos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuario'},
        ),
        migrations.RenameField(
            model_name='categoriacurso',
            old_name='desripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='desripcion',
            new_name='descripcion',
        ),
    ]
